// Mocks generated by Mockito 5.4.5 from annotations
// in karmayogi_mobile/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i29;
import 'dart:io' as _i19;
import 'dart:typed_data' as _i30;
import 'dart:ui' as _i23;

import 'package:flutter/widgets.dart' as _i10;
import 'package:http/http.dart' as _i6;
import 'package:karmayogi_mobile/models/_models/competency_data_model.dart'
    as _i25;
import 'package:karmayogi_mobile/models/_models/nodal_model.dart' as _i22;
import 'package:karmayogi_mobile/models/_models/register_organisation_model.dart'
    as _i11;
import 'package:karmayogi_mobile/models/index.dart' as _i5;
import 'package:karmayogi_mobile/respositories/_respositories/learn_repository.dart'
    as _i24;
import 'package:karmayogi_mobile/respositories/_respositories/profile_repository.dart'
    as _i7;
import 'package:karmayogi_mobile/services/_services/learn_service.dart' as _i4;
import 'package:karmayogi_mobile/services/_services/profile_service.dart'
    as _i2;
import 'package:karmayogi_mobile/services/_services/registration_service.dart'
    as _i3;
import 'package:karmayogi_mobile/ui/pages/_pages/mdo_channels/model/mdo_channel_data_model.dart'
    as _i26;
import 'package:karmayogi_mobile/ui/pages/_pages/search/models/composite_search_model.dart'
    as _i28;
import 'package:karmayogi_mobile/ui/pages/_pages/toc/model/content_state_model.dart'
    as _i27;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/achievement_item_model.dart'
    as _i18;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/connection_relationship_model.dart'
    as _i21;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/designation_model.dart'
    as _i20;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/district_model.dart'
    as _i14;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/education_qualification_item_model.dart'
    as _i17;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/extended_profile_model.dart'
    as _i15;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/profile_field_status_model.dart'
    as _i8;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/service_history_model.dart'
    as _i16;
import 'package:karmayogi_mobile/ui/screens/_screens/profile/model/state_model.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileService_0 extends _i1.SmartFake
    implements _i2.ProfileService {
  _FakeProfileService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegistrationService_1 extends _i1.SmartFake
    implements _i3.RegistrationService {
  _FakeRegistrationService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLearnService_2 extends _i1.SmartFake implements _i4.LearnService {
  _FakeLearnService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourse_3 extends _i1.SmartFake implements _i5.Course {
  _FakeCourse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i7.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileService get profileService => (super.noSuchMethod(
        Invocation.getter(#profileService),
        returnValue: _FakeProfileService_0(
          this,
          Invocation.getter(#profileService),
        ),
      ) as _i2.ProfileService);

  @override
  _i3.RegistrationService get registrationService => (super.noSuchMethod(
        Invocation.getter(#registrationService),
        returnValue: _FakeRegistrationService_1(
          this,
          Invocation.getter(#registrationService),
        ),
      ) as _i3.RegistrationService);

  @override
  List<dynamic> get designationsList => (super.noSuchMethod(
        Invocation.getter(#designationsList),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get groupList => (super.noSuchMethod(
        Invocation.getter(#groupList),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<_i8.ProfileFieldStatusModel> get inReview => (super.noSuchMethod(
        Invocation.getter(#inReview),
        returnValue: <_i8.ProfileFieldStatusModel>[],
      ) as List<_i8.ProfileFieldStatusModel>);

  @override
  List<_i8.ProfileFieldStatusModel> get rejectedFields => (super.noSuchMethod(
        Invocation.getter(#rejectedFields),
        returnValue: <_i8.ProfileFieldStatusModel>[],
      ) as List<_i8.ProfileFieldStatusModel>);

  @override
  List<_i8.ProfileFieldStatusModel> get approvedFields => (super.noSuchMethod(
        Invocation.getter(#approvedFields),
        returnValue: <_i8.ProfileFieldStatusModel>[],
      ) as List<_i8.ProfileFieldStatusModel>);

  @override
  List<_i5.Nationality> get nationalities => (super.noSuchMethod(
        Invocation.getter(#nationalities),
        returnValue: <_i5.Nationality>[],
      ) as List<_i5.Nationality>);

  @override
  List<_i5.Language> get languages => (super.noSuchMethod(
        Invocation.getter(#languages),
        returnValue: <_i5.Language>[],
      ) as List<_i5.Language>);

  @override
  List<dynamic> get organisation => (super.noSuchMethod(
        Invocation.getter(#organisation),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get industries => (super.noSuchMethod(
        Invocation.getter(#industries),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get gradePay => (super.noSuchMethod(
        Invocation.getter(#gradePay),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get services => (super.noSuchMethod(
        Invocation.getter(#services),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get cadre => (super.noSuchMethod(
        Invocation.getter(#cadre),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get graduations => (super.noSuchMethod(
        Invocation.getter(#graduations),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get postGraduations => (super.noSuchMethod(
        Invocation.getter(#postGraduations),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get orgLevelDesignationsList => (super.noSuchMethod(
        Invocation.getter(#orgLevelDesignationsList),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  bool get designationUpdateStatus => (super.noSuchMethod(
        Invocation.getter(#designationUpdateStatus),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  double get profileCompletionPercentage => (super.noSuchMethod(
        Invocation.getter(#profileCompletionPercentage),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<List<_i5.Profile>> getProfileDetails() => (super.noSuchMethod(
        Invocation.method(
          #getProfileDetails,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Profile>>.value(<_i5.Profile>[]),
      ) as _i9.Future<List<_i5.Profile>>);

  @override
  _i9.Future<List<_i5.Profile>> getProfileDetailsById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileDetailsById,
          [id],
        ),
        returnValue: _i9.Future<List<_i5.Profile>>.value(<_i5.Profile>[]),
      ) as _i9.Future<List<_i5.Profile>>);

  @override
  _i9.Future<List<_i5.Nationality>> getNationalities() => (super.noSuchMethod(
        Invocation.method(
          #getNationalities,
          [],
        ),
        returnValue:
            _i9.Future<List<_i5.Nationality>>.value(<_i5.Nationality>[]),
      ) as _i9.Future<List<_i5.Nationality>>);

  @override
  _i9.Future<List<_i5.Language>> getLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getLanguages,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Language>>.value(<_i5.Language>[]),
      ) as _i9.Future<List<_i5.Language>>);

  @override
  _i9.Future<int?> getResendOtpTime() => (super.noSuchMethod(
        Invocation.method(
          #getResendOtpTime,
          [],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i9.Future<List<dynamic>> getDegrees(dynamic type) => (super.noSuchMethod(
        Invocation.method(
          #getDegrees,
          [type],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getOrganisations() => (super.noSuchMethod(
        Invocation.method(
          #getOrganisations,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getIndustries() => (super.noSuchMethod(
        Invocation.method(
          #getIndustries,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getDesignations(
    int? offset,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDesignations,
          [
            offset,
            query,
          ],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getGroups() => (super.noSuchMethod(
        Invocation.method(
          #getGroups,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<_i8.ProfileFieldStatusModel>> getInReviewFields({
    bool? isRejected = false,
    bool? isApproved = false,
    bool? forceUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInReviewFields,
          [],
          {
            #isRejected: isRejected,
            #isApproved: isApproved,
            #forceUpdate: forceUpdate,
          },
        ),
        returnValue: _i9.Future<List<_i8.ProfileFieldStatusModel>>.value(
            <_i8.ProfileFieldStatusModel>[]),
      ) as _i9.Future<List<_i8.ProfileFieldStatusModel>>);

  @override
  _i9.Future<List<dynamic>> getGradePay() => (super.noSuchMethod(
        Invocation.method(
          #getGradePay,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getServices() => (super.noSuchMethod(
        Invocation.method(
          #getServices,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getCadre() => (super.noSuchMethod(
        Invocation.method(
          #getCadre,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<dynamic> getUserName(dynamic wid) => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [wid],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getInsights(_i10.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsights,
          [context],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> profilePhotoUpdate(dynamic image) => (super.noSuchMethod(
        Invocation.method(
          #profilePhotoUpdate,
          [image],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getKarmaPointHistory({
    dynamic limit,
    dynamic offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKarmaPointHistory,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getTotalKarmaPoint() => (super.noSuchMethod(
        Invocation.method(
          #getTotalKarmaPoint,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getKarmaPointCourseRead(String? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKarmaPointCourseRead,
          [courseId],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> claimKarmaPoints(String? courseId) => (super.noSuchMethod(
        Invocation.method(
          #claimKarmaPoints,
          [courseId],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<dynamic>> getRecipientList(
    String? query,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipientList,
          [
            query,
            limit,
          ],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<dynamic> getLeaderboardData() => (super.noSuchMethod(
        Invocation.method(
          #getLeaderboardData,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> requestForService({
    required _i10.BuildContext? context,
    required String? typeOfCivilService,
    required String? service,
    String? cadreControllingAuthority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestForService,
          [],
          {
            #context: context,
            #typeOfCivilService: typeOfCivilService,
            #service: service,
            #cadreControllingAuthority: cadreControllingAuthority,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getCadreConfigData() => (super.noSuchMethod(
        Invocation.method(
          #getCadreConfigData,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<String>> getRecommendedCourse() => (super.noSuchMethod(
        Invocation.method(
          #getRecommendedCourse,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<_i5.RegistrationLinkModel?> getOrgFrameworkId({String? orgId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrgFrameworkId,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<_i5.RegistrationLinkModel?>.value(),
      ) as _i9.Future<_i5.RegistrationLinkModel?>);

  @override
  _i9.Future<List<dynamic>> getOrgBasedDesignations(
    String? orgId, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrgBasedDesignations,
          [orgId],
          {#notify: notify},
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<_i11.OrganisationModel?> getOrganizationData(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationData,
          [orgId],
        ),
        returnValue: _i9.Future<_i11.OrganisationModel?>.value(),
      ) as _i9.Future<_i11.OrganisationModel?>);

  @override
  _i9.Future<String> generateEmailOTP(String? emailAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateEmailOTP,
          [emailAddress],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateEmailOTP,
            [emailAddress],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> generateEmailExtOTP(String? emailAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateEmailExtOTP,
          [emailAddress],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateEmailExtOTP,
            [emailAddress],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> verifyEmailOTP(
    String? emailId,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmailOTP,
          [
            emailId,
            otp,
          ],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #verifyEmailOTP,
            [
              emailId,
              otp,
            ],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<List<String>> getApprovedEmailDomains() => (super.noSuchMethod(
        Invocation.method(
          #getApprovedEmailDomains,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<dynamic> generatePrimaryEmailOTP(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePrimaryEmailOTP,
          [email],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<String> verifyPrimaryEmailOTP(
    String? emailId,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPrimaryEmailOTP,
          [
            emailId,
            otp,
          ],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #verifyPrimaryEmailOTP,
            [
              emailId,
              otp,
            ],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> getRegisterLinkValidated(String? link) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegisterLinkValidated,
          [link],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getRegisterLinkValidated,
            [link],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> generateMobileNumberOTP(String? mobileNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMobileNumberOTP,
          [mobileNumber],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateMobileNumberOTP,
            [mobileNumber],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<dynamic> verifyMobileNumberOTP(
    String? mobileNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyMobileNumberOTP,
          [
            mobileNumber,
            otp,
          ],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<String> getSelfRegister({
    required String? fullName,
    required String? email,
    required String? group,
    required String? mobileNumber,
    required _i11.OrganisationModel? organisation,
    required String? designation,
    required String? registrationLink,
    bool? isWhatsappConsent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelfRegister,
          [],
          {
            #fullName: fullName,
            #email: email,
            #group: group,
            #mobileNumber: mobileNumber,
            #organisation: organisation,
            #designation: designation,
            #registrationLink: registrationLink,
            #isWhatsappConsent: isWhatsappConsent,
          },
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getSelfRegister,
            [],
            {
              #fullName: fullName,
              #email: email,
              #group: group,
              #mobileNumber: mobileNumber,
              #organisation: organisation,
              #designation: designation,
              #registrationLink: registrationLink,
              #isWhatsappConsent: isWhatsappConsent,
            },
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> withdrawDesignation({required String? wfId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #withdrawDesignation,
          [],
          {#wfId: wfId},
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #withdrawDesignation,
            [],
            {#wfId: wfId},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  void designationStatus(bool? value) => super.noSuchMethod(
        Invocation.method(
          #designationStatus,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<dynamic> updateProfileDetails(
          Map<dynamic, dynamic>? profileDetails) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileDetails,
          [profileDetails],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<_i5.Profile?> getBasicProfileDetailsById(
    String? id, {
    bool? isCurrentUser = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBasicProfileDetailsById,
          [id],
          {#isCurrentUser: isCurrentUser},
        ),
        returnValue: _i9.Future<_i5.Profile?>.value(),
      ) as _i9.Future<_i5.Profile?>);

  @override
  _i9.Future<List<_i13.StateModel>> getStateList() => (super.noSuchMethod(
        Invocation.method(
          #getStateList,
          [],
        ),
        returnValue:
            _i9.Future<List<_i13.StateModel>>.value(<_i13.StateModel>[]),
      ) as _i9.Future<List<_i13.StateModel>>);

  @override
  _i9.Future<List<_i14.DistrictModel>> getDistrictList(String? state) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistrictList,
          [state],
        ),
        returnValue:
            _i9.Future<List<_i14.DistrictModel>>.value(<_i14.DistrictModel>[]),
      ) as _i9.Future<List<_i14.DistrictModel>>);

  @override
  _i9.Future<String> saveExtendedProfile(Map<String, dynamic>? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveExtendedProfile,
          [content],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #saveExtendedProfile,
            [content],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i15.ExtendedProfile?> getExtendedProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtendedProfile,
          [userId],
        ),
        returnValue: _i9.Future<_i15.ExtendedProfile?>.value(),
      ) as _i9.Future<_i15.ExtendedProfile?>);

  @override
  _i9.Future<List<String>> getDegreeList() => (super.noSuchMethod(
        Invocation.method(
          #getDegreeList,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> getInstitutionList() => (super.noSuchMethod(
        Invocation.method(
          #getInstitutionList,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<String> updateExtendedProfile(Map<String, dynamic>? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExtendedProfile,
          [content],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #updateExtendedProfile,
            [content],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<List<_i16.ServiceHistoryModel>> getExtendedServiceHistory(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtendedServiceHistory,
          [userId],
        ),
        returnValue: _i9.Future<List<_i16.ServiceHistoryModel>>.value(
            <_i16.ServiceHistoryModel>[]),
      ) as _i9.Future<List<_i16.ServiceHistoryModel>>);

  @override
  _i9.Future<List<_i17.EducationalQualificationItem>>
      getExtendedEducationHistory(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getExtendedEducationHistory,
              [userId],
            ),
            returnValue:
                _i9.Future<List<_i17.EducationalQualificationItem>>.value(
                    <_i17.EducationalQualificationItem>[]),
          ) as _i9.Future<List<_i17.EducationalQualificationItem>>);

  @override
  _i9.Future<List<_i18.AchievementItem>> getExtendedAchievements(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtendedAchievements,
          [userId],
        ),
        returnValue: _i9.Future<List<_i18.AchievementItem>>.value(
            <_i18.AchievementItem>[]),
      ) as _i9.Future<List<_i18.AchievementItem>>);

  @override
  _i9.Future<String?> uploadProfileBanner(_i19.File? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfileBanner,
          [image],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<Map<String, dynamic>?> uploadAchievementCertificate(
          _i19.File? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAchievementCertificate,
          [image],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<String> updateDegreeMasterList(String? degree) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDegreeMasterList,
          [degree],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #updateDegreeMasterList,
            [degree],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> updateInstitutionMasterList(String? institution) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInstitutionMasterList,
          [institution],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #updateInstitutionMasterList,
            [institution],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<List<_i11.OrganisationModel>> getOrgMasterList({
    int? offset = 0,
    String? query = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrgMasterList,
          [],
          {
            #offset: offset,
            #query: query,
          },
        ),
        returnValue: _i9.Future<List<_i11.OrganisationModel>>.value(
            <_i11.OrganisationModel>[]),
      ) as _i9.Future<List<_i11.OrganisationModel>>);

  @override
  _i9.Future<List<_i20.DesignationModel>> getOrgBasedDesignationList({
    int? offset = 0,
    required List<String>? orgIdList,
    String? query = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrgBasedDesignationList,
          [],
          {
            #offset: offset,
            #orgIdList: orgIdList,
            #query: query,
          },
        ),
        returnValue: _i9.Future<List<_i20.DesignationModel>>.value(
            <_i20.DesignationModel>[]),
      ) as _i9.Future<List<_i20.DesignationModel>>);

  @override
  _i9.Future<_i21.ConnectionRelationshipModel?> getConnectionRelationship(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConnectionRelationship,
          [id],
        ),
        returnValue: _i9.Future<_i21.ConnectionRelationshipModel?>.value(),
      ) as _i9.Future<_i21.ConnectionRelationshipModel?>);

  @override
  void clearProfileDetails() => super.noSuchMethod(
        Invocation.method(
          #clearProfileDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<List<_i22.NodalModel>> getNodalUser() => (super.noSuchMethod(
        Invocation.method(
          #getNodalUser,
          [],
        ),
        returnValue:
            _i9.Future<List<_i22.NodalModel>>.value(<_i22.NodalModel>[]),
      ) as _i9.Future<List<_i22.NodalModel>>);

  @override
  void addListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LearnRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLearnRepository extends _i1.Mock implements _i24.LearnRepository {
  MockLearnRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LearnService get learnService => (super.noSuchMethod(
        Invocation.getter(#learnService),
        returnValue: _FakeLearnService_2(
          this,
          Invocation.getter(#learnService),
        ),
      ) as _i4.LearnService);

  @override
  List<_i5.BrowseCompetencyCardModel> get browseCompetencyCard =>
      (super.noSuchMethod(
        Invocation.getter(#browseCompetencyCard),
        returnValue: <_i5.BrowseCompetencyCardModel>[],
      ) as List<_i5.BrowseCompetencyCardModel>);

  @override
  set browseCompetencyCard(
          List<_i5.BrowseCompetencyCardModel>? _browseCompetencyCard) =>
      super.noSuchMethod(
        Invocation.setter(
          #browseCompetencyCard,
          _browseCompetencyCard,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.ProviderCardModel> get providerCardModel => (super.noSuchMethod(
        Invocation.getter(#providerCardModel),
        returnValue: <_i5.ProviderCardModel>[],
      ) as List<_i5.ProviderCardModel>);

  @override
  set providerCardModel(List<_i5.ProviderCardModel>? _providerCardModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #providerCardModel,
          _providerCardModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.Course> get courses => (super.noSuchMethod(
        Invocation.getter(#courses),
        returnValue: <_i5.Course>[],
      ) as List<_i5.Course>);

  @override
  set courses(List<_i5.Course>? _courses) => super.noSuchMethod(
        Invocation.setter(
          #courses,
          _courses,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set trendingCourseDeptList(dynamic _trendingCourseDeptList) =>
      super.noSuchMethod(
        Invocation.setter(
          #trendingCourseDeptList,
          _trendingCourseDeptList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set netcoreConfig(dynamic _netcoreConfig) => super.noSuchMethod(
        Invocation.setter(
          #netcoreConfig,
          _netcoreConfig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i25.CompetencyTheme> get competencyThemeList => (super.noSuchMethod(
        Invocation.getter(#competencyThemeList),
        returnValue: <_i25.CompetencyTheme>[],
      ) as List<_i25.CompetencyTheme>);

  @override
  List<_i5.Course> get exteranlCourses => (super.noSuchMethod(
        Invocation.getter(#exteranlCourses),
        returnValue: <_i5.Course>[],
      ) as List<_i5.Course>);

  @override
  Map<String, dynamic> get languageProgress => (super.noSuchMethod(
        Invocation.getter(#languageProgress),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<List<_i5.BrowseCompetencyCardModel>> getListOfCompetencies(
          dynamic context) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfCompetencies,
          [context],
        ),
        returnValue: _i9.Future<List<_i5.BrowseCompetencyCardModel>>.value(
            <_i5.BrowseCompetencyCardModel>[]),
      ) as _i9.Future<List<_i5.BrowseCompetencyCardModel>>);

  @override
  _i9.Future<List<_i5.ProviderCardModel>> getListOfProviders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfProviders,
          [],
        ),
        returnValue: _i9.Future<List<_i5.ProviderCardModel>>.value(
            <_i5.ProviderCardModel>[]),
      ) as _i9.Future<List<_i5.ProviderCardModel>>);

  @override
  _i9.Future<List<_i5.Course>> getCourses(
    int? pageNo,
    String? searchText,
    List<dynamic>? primaryCategory,
    List<dynamic>? mimeType,
    List<dynamic>? source, {
    bool? isCollection = false,
    bool? isInviteOnlyStandaloneAssesment = false,
    Duration? ttl,
    bool? hasRequestBody = false,
    bool? isModerated = false,
    Map<String, dynamic>? requestBody,
    bool? checkforCBPEnddate = true,
    List<String>? doIdList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourses,
          [
            pageNo,
            searchText,
            primaryCategory,
            mimeType,
            source,
          ],
          {
            #isCollection: isCollection,
            #isInviteOnlyStandaloneAssesment: isInviteOnlyStandaloneAssesment,
            #ttl: ttl,
            #hasRequestBody: hasRequestBody,
            #isModerated: isModerated,
            #requestBody: requestBody,
            #checkforCBPEnddate: checkforCBPEnddate,
            #doIdList: doIdList,
          },
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<_i5.Course> getExternalCourseContents({required String? extId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExternalCourseContents,
          [],
          {#extId: extId},
        ),
        returnValue: _i9.Future<_i5.Course>.value(_FakeCourse_3(
          this,
          Invocation.method(
            #getExternalCourseContents,
            [],
            {#extId: extId},
          ),
        )),
      ) as _i9.Future<_i5.Course>);

  @override
  _i9.Future<List<_i5.Course>> getKarmaProgramContents(
    String? primaryCategory, {
    bool? hasRequestBody = false,
    required String? url,
    Map<String, dynamic>? requestBody,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKarmaProgramContents,
          [primaryCategory],
          {
            #hasRequestBody: hasRequestBody,
            #url: url,
            #requestBody: requestBody,
          },
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<List<dynamic>> addCBPEnddateToCourse(List<dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCBPEnddateToCourse,
          [body],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<_i5.Course>> getCoursesByCollection(String? identifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursesByCollection,
          [identifier],
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<List<_i5.Course>> getCoursesByCompetencies(
    dynamic competencyName,
    dynamic selectedTypes,
    dynamic selectedProviders,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursesByCompetencies,
          [
            competencyName,
            selectedTypes,
            selectedProviders,
          ],
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<List<_i5.Course>> getCoursesByProvider(
    String? providerName,
    List<String>? selectedTypes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursesByProvider,
          [
            providerName,
            selectedTypes,
          ],
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<List<_i5.Batch>> getBatchList(dynamic courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchList,
          [courseId],
        ),
        returnValue: _i9.Future<List<_i5.Batch>>.value(<_i5.Batch>[]),
      ) as _i9.Future<List<_i5.Batch>>);

  @override
  _i9.Future<Map<dynamic, dynamic>?> getSurveyForm(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurveyForm,
          [id],
        ),
        returnValue: _i9.Future<Map<dynamic, dynamic>?>.value(),
      ) as _i9.Future<Map<dynamic, dynamic>?>);

  @override
  _i9.Future<_i5.CbPlanModel?> getCbplan() => (super.noSuchMethod(
        Invocation.method(
          #getCbplan,
          [],
        ),
        returnValue: _i9.Future<_i5.CbPlanModel?>.value(),
      ) as _i9.Future<_i5.CbPlanModel?>);

  @override
  _i9.Future<dynamic> getCompetencySearchInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCompetencySearchInfo,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getCompetencySearchInfoFilter() => (super.noSuchMethod(
        Invocation.method(
          #getCompetencySearchInfoFilter,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getSearchByProvider() => (super.noSuchMethod(
        Invocation.method(
          #getSearchByProvider,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<void> getCompetency() => (super.noSuchMethod(
        Invocation.method(
          #getCompetency,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<dynamic> getCourseData(
    dynamic id, {
    bool? isFeatured = false,
    bool? isResource = false,
    bool? pointToProd = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseData,
          [id],
          {
            #isFeatured: isFeatured,
            #isResource: isResource,
            #pointToProd: pointToProd,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getCourseReviewSummery({
    required String? courseId,
    required String? primaryCategory,
    bool? forceUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseReviewSummery,
          [],
          {
            #courseId: courseId,
            #primaryCategory: primaryCategory,
            #forceUpdate: forceUpdate,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getCourseDetails(
    dynamic id, {
    bool? isFeatured = false,
    bool? pointToProd = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseDetails,
          [id],
          {
            #isFeatured: isFeatured,
            #pointToProd: pointToProd,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getYourReview({
    required String? id,
    required String? primaryCategory,
    bool? forceUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getYourReview,
          [],
          {
            #id: id,
            #primaryCategory: primaryCategory,
            #forceUpdate: forceUpdate,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  void clearCourseDetails() => super.noSuchMethod(
        Invocation.method(
          #clearCourseDetails,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCbplan() => super.noSuchMethod(
        Invocation.method(
          #clearCbplan,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<List<_i5.ProviderCardModel>> getListOfFeaturedProviders(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfFeaturedProviders,
          [id],
        ),
        returnValue: _i9.Future<List<_i5.ProviderCardModel>>.value(
            <_i5.ProviderCardModel>[]),
      ) as _i9.Future<List<_i5.ProviderCardModel>>);

  @override
  _i9.Future<dynamic> getMicroSiteFormData({
    String? orgId,
    String? type,
    String? subtype = 'microsite-v2',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroSiteFormData,
          [],
          {
            #orgId: orgId,
            #type: type,
            #subtype: subtype,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getLearnerReviews(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getLearnerReviews,
          [id],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMicroSiteCompetencies({
    required String? orgId,
    required String? competencyArea,
    required List<String>? facets,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroSiteCompetencies,
          [],
          {
            #orgId: orgId,
            #competencyArea: competencyArea,
            #facets: facets,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getInsightData({String? orgId}) => (super.noSuchMethod(
        Invocation.method(
          #getInsightData,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMicroSiteTopCourses(
    String? orgId,
    List<String>? selectedTypes,
    String? selectedCoursePills,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroSiteTopCourses,
          [
            orgId,
            selectedTypes,
            selectedCoursePills,
            limit,
          ],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMicroSiteFeaturedCourses(
    String? orgId,
    List<String>? selectedTypes,
    String? selectedCoursePills,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroSiteFeaturedCourses,
          [
            orgId,
            selectedTypes,
            selectedCoursePills,
          ],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMicroSiteCalenderData(
    String? id,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMicroSiteCalenderData,
          [
            id,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<_i26.MdoChannelDataModel>> getListOfMdoChannels(
          String? orgBookmarkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfMdoChannels,
          [orgBookmarkId],
        ),
        returnValue: _i9.Future<List<_i26.MdoChannelDataModel>>.value(
            <_i26.MdoChannelDataModel>[]),
      ) as _i9.Future<List<_i26.MdoChannelDataModel>>);

  @override
  _i9.Future<dynamic> getMdoChannelFormData({required String? orgId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMdoChannelFormData,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getChannelInsightData({required String? orgId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelInsightData,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMdoCertificateOfWeek(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMdoCertificateOfWeek,
          [orgId],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMdoCoursesData(
    String? orgId,
    String? type,
    String? selectedCoursePills,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMdoCoursesData,
          [
            orgId,
            type,
            selectedCoursePills,
          ],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getAnnouncementData({required String? orgId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnnouncementData,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getMDOTopLearnerData({required String? orgId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMDOTopLearnerData,
          [],
          {#orgId: orgId},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> getCompetenciesByOrg(String? orgId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompetenciesByOrg,
          [orgId],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<_i27.ContentStateModel>> readContentProgress(
    String? courseId,
    String? batchId, {
    List<dynamic>? contentIds = const [],
    required String? language,
    bool? forceUpdateOverallProgress = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readContentProgress,
          [
            courseId,
            batchId,
          ],
          {
            #contentIds: contentIds,
            #language: language,
            #forceUpdateOverallProgress: forceUpdateOverallProgress,
          },
        ),
        returnValue: _i9.Future<List<_i27.ContentStateModel>>.value(
            <_i27.ContentStateModel>[]),
      ) as _i9.Future<List<_i27.ContentStateModel>>);

  @override
  void resetLanguageProgress() => super.noSuchMethod(
        Invocation.method(
          #resetLanguageProgress,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<List<_i27.ContentStateModel>> readPreRequisiteContentProgress(
          List<String>? contentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #readPreRequisiteContentProgress,
          [contentIds],
        ),
        returnValue: _i9.Future<List<_i27.ContentStateModel>>.value(
            <_i27.ContentStateModel>[]),
      ) as _i9.Future<List<_i27.ContentStateModel>>);

  @override
  _i9.Future<bool> isSmartechEventEnabled({
    required String? eventName,
    bool? reload = false,
    bool? isFunctionality = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSmartechEventEnabled,
          [],
          {
            #eventName: eventName,
            #reload: reload,
            #isFunctionality: isFunctionality,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i5.Course>> getRecommendationWithDoId(
    List<dynamic>? doIdList, {
    List<String>? relevantDoId,
    bool? pointToProd = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationWithDoId,
          [doIdList],
          {
            #relevantDoId: relevantDoId,
            #pointToProd: pointToProd,
          },
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  void updateRelevance(
    List<String>? relevantDoId,
    List<_i5.Course>? courses,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRelevance,
          [
            relevantDoId,
            courses,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<List<_i5.Course>> getCourseEnrollDetailsByIds({
    required List<String>? courseIds,
    bool? checkforCBPEnddate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseEnrollDetailsByIds,
          [],
          {
            #courseIds: courseIds,
            #checkforCBPEnddate: checkforCBPEnddate,
          },
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<_i5.UserEnrollmentInfo?> getEnrollmentSummary() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnrollmentSummary,
          [],
        ),
        returnValue: _i9.Future<_i5.UserEnrollmentInfo?>.value(),
      ) as _i9.Future<_i5.UserEnrollmentInfo?>);

  @override
  _i9.Future<List<_i5.Course>> getEnrollmentListByFilter({
    required String? status,
    int? limit,
    String? contentType,
    bool? retiredCoursesEnabled = true,
    bool? checkforCBPEnddate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnrollmentListByFilter,
          [],
          {
            #status: status,
            #limit: limit,
            #contentType: contentType,
            #retiredCoursesEnabled: retiredCoursesEnabled,
            #checkforCBPEnddate: checkforCBPEnddate,
          },
        ),
        returnValue: _i9.Future<List<_i5.Course>>.value(<_i5.Course>[]),
      ) as _i9.Future<List<_i5.Course>>);

  @override
  _i9.Future<String> enrollToCuratedProgram(
    String? courseId,
    String? batchId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enrollToCuratedProgram,
          [
            courseId,
            batchId,
          ],
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #enrollToCuratedProgram,
            [
              courseId,
              batchId,
            ],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> enrollProgram({
    required String? courseId,
    required String? programId,
    required String? batchId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enrollProgram,
          [],
          {
            #courseId: courseId,
            #programId: programId,
            #batchId: batchId,
          },
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #enrollProgram,
            [],
            {
              #courseId: courseId,
              #programId: programId,
              #batchId: batchId,
            },
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<dynamic> autoEnrollBatch({
    required String? courseId,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoEnrollBatch,
          [],
          {
            #courseId: courseId,
            #language: language,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<String?> getCourseCompletionCertificate(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseCompletionCertificate,
          [id],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<String?> getCourseCompletionDynamicCertificate(
    String? courseId,
    String? batchId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseCompletionDynamicCertificate,
          [
            courseId,
            batchId,
          ],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<dynamic> downloadCompletionCertificate(
    String? printUri, {
    String? outputType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadCompletionCertificate,
          [printUri],
          {#outputType: outputType},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<_i28.CompositeSearchModel?> getCompositeSearchData(
    int? pageNo,
    String? searchText,
    List<dynamic>? primaryCategory,
    List<dynamic>? mimeType,
    List<dynamic>? source, {
    Duration? ttl,
    bool? checkforCBPEnddate = true,
    List<String>? facets,
    Map<String, dynamic>? filters,
    Map<String, dynamic>? sortBy,
    int? limit,
    List<String>? fields = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompositeSearchData,
          [
            pageNo,
            searchText,
            primaryCategory,
            mimeType,
            source,
          ],
          {
            #ttl: ttl,
            #checkforCBPEnddate: checkforCBPEnddate,
            #facets: facets,
            #filters: filters,
            #sortBy: sortBy,
            #limit: limit,
            #fields: fields,
          },
        ),
        returnValue: _i9.Future<_i28.CompositeSearchModel?>.value(),
      ) as _i9.Future<_i28.CompositeSearchModel?>);

  @override
  void addListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i23.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i6.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<_i6.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i30.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i30.Uint8List>.value(_i30.Uint8List(0)),
      ) as _i9.Future<_i30.Uint8List>);

  @override
  _i9.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_5(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
