// pages
export './pages/course_progress_skeleton_page.dart';
export './pages/home_skeleton_page.dart';
export './pages/course_card_skeleton_page.dart';
export './pages/card_skeleton.dart';
export './pages/competency_passbook_skeleton.dart';
export './pages/competency_passbook_theme_skeleton_page.dart';
export './pages/course_card_vertical_skeleton_page.dart';
export './pages/toc_skeleton.dart';
export './pages/toc_content_header_skeleton.dart';
export './pages/toc_about_skeleton.dart';
export './pages/toc_content_skeleton.dart';
export './pages/toc_player_skeleton.dart';

// widget
export './widgets/container_skeleton.dart';
export './widgets/myacticities_card_skeleton.dart';
export './widgets/tab_skeleton.dart';
export './widgets/course_card_skeleton.dart';
export './widgets/stats_skeleton.dart';
export './widgets/weeklyclap_skeleton.dart';
export './widgets/discuss_skeleton.dart';
export './widgets/toc_overview_icons_skeleton.dart';
