// Mocks generated by Mockito 5.4.5 from annotations
// in karmayogi_mobile/test/ui/screens/discussion_hub/screens/community_view/_screens/community_home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;
import 'dart:ui' as _i12;

import 'package:karmayogi_mobile/ui/pages/_pages/search/models/community_search_model.dart'
    as _i10;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/repositories/discussion_repository.dart'
    as _i2;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/community_view/_models/community_detail_model.dart'
    as _i6;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/community_view/_models/community_member_model.dart'
    as _i9;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/community_view/_models/community_model.dart'
    as _i5;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/community_view/_models/user_community_model.dart'
    as _i7;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/discussion/add_discussion/_models/tag_user_data_model.dart'
    as _i11;
import 'package:karmayogi_mobile/ui/widgets/_discussion_hub/screens/discussion/discussion_view/_models/discussion_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DiscussionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscussionRepository extends _i1.Mock
    implements _i2.DiscussionRepository {
  MockDiscussionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.DiscussionModel?> getDiscussion(
    int? pageNumber,
    String? searchQuery,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscussion,
          [
            pageNumber,
            searchQuery,
            communityId,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionModel?> getMediaDiscussion(
    int? pageNumber,
    String? searchQuery,
    String? communityId,
    List<String>? categoryType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaDiscussion,
          [
            pageNumber,
            searchQuery,
            communityId,
            categoryType,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionModel?> getBookmarkedDiscussion(
    int? pageNumber,
    String? searchQuery,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedDiscussion,
          [
            pageNumber,
            searchQuery,
            communityId,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionModel?> getGlobalDiscussion(
    int? pageNumber,
    String? searchQuery,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalDiscussion,
          [
            pageNumber,
            searchQuery,
            communityId,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionModel?> getMyDiscussion(
    int? pageNumber,
    String? searchQuery,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyDiscussion,
          [
            pageNumber,
            searchQuery,
            communityId,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionModel?> getReply(
    String? communityId,
    String? parentDiscussionId,
    int? pageNumber,
    bool? isAnswerPostReply,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReply,
          [
            communityId,
            parentDiscussionId,
            pageNumber,
            isAnswerPostReply,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionModel?>.value(),
      ) as _i3.Future<_i4.DiscussionModel?>);

  @override
  _i3.Future<_i4.DiscussionEnrichData?> getEnrichData(
    String? requestType,
    List<Map<String, dynamic>>? communityFilters,
    List<String>? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnrichData,
          [
            requestType,
            communityFilters,
            filter,
          ],
        ),
        returnValue: _i3.Future<_i4.DiscussionEnrichData?>.value(),
      ) as _i3.Future<_i4.DiscussionEnrichData?>);

  @override
  _i3.Future<dynamic> likeComment(
    String? discussionId,
    String? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #likeComment,
          [
            discussionId,
            endPoint,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> dislikeComment(
    String? discussionId,
    String? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dislikeComment,
          [
            discussionId,
            endPoint,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> bookmarkComment(
    String? discussionId,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookmarkComment,
          [
            discussionId,
            communityId,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> unBookmarkComment(
    String? discussionId,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBookmarkComment,
          [
            discussionId,
            communityId,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> reportDiscussion(
    String? discussionId,
    String? discussionText,
    List<String>? reportReasons,
    String? otherComment,
    String? postType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportDiscussion,
          [
            discussionId,
            discussionText,
            reportReasons,
            otherComment,
            postType,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<List<String>> getReportReasons() => (super.noSuchMethod(
        Invocation.method(
          #getReportReasons,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<dynamic> deleteDiscussion(
    String? discussionId,
    String? endPoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDiscussion,
          [
            discussionId,
            endPoint,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i5.CommunityModel?> getCommunity({
    required int? pageNumber,
    String? searchQuery,
    String? topicName,
    int? pageSize,
    List<String>? facets,
    String? orderBy = '',
    String? orderDirection = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommunity,
          [],
          {
            #pageNumber: pageNumber,
            #searchQuery: searchQuery,
            #topicName: topicName,
            #pageSize: pageSize,
            #facets: facets,
            #orderBy: orderBy,
            #orderDirection: orderDirection,
          },
        ),
        returnValue: _i3.Future<_i5.CommunityModel?>.value(),
      ) as _i3.Future<_i5.CommunityModel?>);

  @override
  _i3.Future<_i5.CommunityModel?> getPopularCommunity() => (super.noSuchMethod(
        Invocation.method(
          #getPopularCommunity,
          [],
        ),
        returnValue: _i3.Future<_i5.CommunityModel?>.value(),
      ) as _i3.Future<_i5.CommunityModel?>);

  @override
  _i3.Future<_i6.CommunityDetailModel?> getCommunityDetails(
          String? communityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommunityDetails,
          [communityId],
        ),
        returnValue: _i3.Future<_i6.CommunityDetailModel?>.value(),
      ) as _i3.Future<_i6.CommunityDetailModel?>);

  @override
  _i3.Future<dynamic> joinCommunity(String? communityId) => (super.noSuchMethod(
        Invocation.method(
          #joinCommunity,
          [communityId],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> leftCommunity(String? communityId) => (super.noSuchMethod(
        Invocation.method(
          #leftCommunity,
          [communityId],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<List<_i7.UserCommunityIdData>> getUserJoinedCommunities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserJoinedCommunities,
          [],
        ),
        returnValue: _i3.Future<List<_i7.UserCommunityIdData>>.value(
            <_i7.UserCommunityIdData>[]),
      ) as _i3.Future<List<_i7.UserCommunityIdData>>);

  @override
  _i3.Future<List<_i5.CommunityItemData>> getUserJoinedCommunitiesListData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserJoinedCommunitiesListData,
          [],
        ),
        returnValue: _i3.Future<List<_i5.CommunityItemData>>.value(
            <_i5.CommunityItemData>[]),
      ) as _i3.Future<List<_i5.CommunityItemData>>);

  @override
  _i3.Future<_i4.DiscussionItemData?> postDiscussion({
    required String? type,
    required String? description,
    required String? communityId,
    required List<Map<String, String>>? mentionedUsers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postDiscussion,
          [],
          {
            #type: type,
            #description: description,
            #communityId: communityId,
            #mentionedUsers: mentionedUsers,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<_i4.DiscussionItemData?> updateDiscussion({
    required String? discussionId,
    required String? type,
    required String? description,
    required String? communityId,
    required List<String>? categoryType,
    required Map<String, List<String>>? mediaCategory,
    required List<Map<String, String>>? mentionedUsers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDiscussion,
          [],
          {
            #discussionId: discussionId,
            #type: type,
            #description: description,
            #communityId: communityId,
            #categoryType: categoryType,
            #mediaCategory: mediaCategory,
            #mentionedUsers: mentionedUsers,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<_i4.DiscussionItemData?> saveDiscussionMedia({
    required String? discussionId,
    required String? communityId,
    required List<String>? categoryType,
    required Map<String, List<String>>? mediaCategory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDiscussionMedia,
          [],
          {
            #discussionId: discussionId,
            #communityId: communityId,
            #categoryType: categoryType,
            #mediaCategory: mediaCategory,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<dynamic> uploadMedia(
    _i8.File? file,
    String? discussionId,
    String? communityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            file,
            discussionId,
            communityId,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i4.DiscussionItemData?> createAnswerPost({
    required String? parentDiscussionId,
    String? parentAnswerPostId,
    required String? type,
    required String? description,
    required String? communityId,
    required bool? isAnswerPostReply,
    required List<Map<String, String>>? mentionedUsers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAnswerPost,
          [],
          {
            #parentDiscussionId: parentDiscussionId,
            #parentAnswerPostId: parentAnswerPostId,
            #type: type,
            #description: description,
            #communityId: communityId,
            #isAnswerPostReply: isAnswerPostReply,
            #mentionedUsers: mentionedUsers,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<_i4.DiscussionItemData?> updateAnswerPost({
    required String? answerPostId,
    required String? description,
    required List<String>? categoryType,
    required Map<String, List<String>>? mediaCategory,
    bool? isInitialUpload = false,
    required bool? isAnswerPostReply,
    required List<Map<String, String>>? mentionedUsers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAnswerPost,
          [],
          {
            #answerPostId: answerPostId,
            #description: description,
            #categoryType: categoryType,
            #mediaCategory: mediaCategory,
            #isInitialUpload: isInitialUpload,
            #isAnswerPostReply: isAnswerPostReply,
            #mentionedUsers: mentionedUsers,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<_i9.CommunityMemberModel?> getCommunityMembers({
    required int? pageNumber,
    String? searchQuery,
    required String? communityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommunityMembers,
          [],
          {
            #pageNumber: pageNumber,
            #searchQuery: searchQuery,
            #communityId: communityId,
          },
        ),
        returnValue: _i3.Future<_i9.CommunityMemberModel?>.value(),
      ) as _i3.Future<_i9.CommunityMemberModel?>);

  @override
  _i3.Future<_i9.CommunityMemberModel?> searchCommunityMembers({
    required int? pageNumber,
    String? searchQuery,
    required String? communityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCommunityMembers,
          [],
          {
            #pageNumber: pageNumber,
            #searchQuery: searchQuery,
            #communityId: communityId,
          },
        ),
        returnValue: _i3.Future<_i9.CommunityMemberModel?>.value(),
      ) as _i3.Future<_i9.CommunityMemberModel?>);

  @override
  _i3.Future<dynamic> reportCommunity(
    String? communityId,
    List<String>? reportReasons,
    String? otherComment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportCommunity,
          [
            communityId,
            reportReasons,
            otherComment,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i10.CommunitySearchModel?> searchCommunity({
    required int? pageNumber,
    String? searchQuery,
    String? topicName,
    int? pageSize,
    List<String>? facets,
    String? orderBy = '',
    String? orderDirection = '',
    Map<String, dynamic>? filters,
    Map<String, dynamic>? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCommunity,
          [],
          {
            #pageNumber: pageNumber,
            #searchQuery: searchQuery,
            #topicName: topicName,
            #pageSize: pageSize,
            #facets: facets,
            #orderBy: orderBy,
            #orderDirection: orderDirection,
            #filters: filters,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i3.Future<_i10.CommunitySearchModel?>.value(),
      ) as _i3.Future<_i10.CommunitySearchModel?>);

  @override
  _i3.Future<_i4.DiscussionItemData?> getDiscussionById({
    required String? communityId,
    required String? discussionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscussionById,
          [],
          {
            #communityId: communityId,
            #discussionId: discussionId,
          },
        ),
        returnValue: _i3.Future<_i4.DiscussionItemData?>.value(),
      ) as _i3.Future<_i4.DiscussionItemData?>);

  @override
  _i3.Future<List<_i11.TagUserDataModel>> getUserListForTagging(
          String? searchText) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserListForTagging,
          [searchText],
        ),
        returnValue: _i3.Future<List<_i11.TagUserDataModel>>.value(
            <_i11.TagUserDataModel>[]),
      ) as _i3.Future<List<_i11.TagUserDataModel>>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
