// Mocks generated by Mockito 5.4.5 from annotations
// in karmayogi_mobile/test/ui/widgets/self_register_qrscanner_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:image_picker/image_picker.dart' as _i8;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_code_scanner_plus/src/qr_code_scanner.dart' as _i4;
import 'package:qr_code_scanner_plus/src/types/barcode.dart' as _i6;
import 'package:qr_code_scanner_plus/src/types/camera.dart' as _i7;
import 'package:qr_code_scanner_plus/src/types/features.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSystemFeatures_0 extends _i1.SmartFake
    implements _i2.SystemFeatures {
  _FakeSystemFeatures_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_1 extends _i1.SmartFake
    implements _i3.LostDataResponse {
  _FakeLostDataResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QRViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRViewController extends _i1.Mock implements _i4.QRViewController {
  MockQRViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
      ) as bool);

  @override
  set disposed(bool? _disposed) => super.noSuchMethod(
        Invocation.setter(
          #disposed,
          _disposed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i6.Barcode> get scannedDataStream => (super.noSuchMethod(
        Invocation.getter(#scannedDataStream),
        returnValue: _i5.Stream<_i6.Barcode>.empty(),
      ) as _i5.Stream<_i6.Barcode>);

  @override
  bool get hasPermissions => (super.noSuchMethod(
        Invocation.getter(#hasPermissions),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i7.CameraFacing> getCameraInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCameraInfo,
          [],
        ),
        returnValue: _i5.Future<_i7.CameraFacing>.value(_i7.CameraFacing.back),
      ) as _i5.Future<_i7.CameraFacing>);

  @override
  _i5.Future<_i7.CameraFacing> flipCamera() => (super.noSuchMethod(
        Invocation.method(
          #flipCamera,
          [],
        ),
        returnValue: _i5.Future<_i7.CameraFacing>.value(_i7.CameraFacing.back),
      ) as _i5.Future<_i7.CameraFacing>);

  @override
  _i5.Future<bool?> getFlashStatus() => (super.noSuchMethod(
        Invocation.method(
          #getFlashStatus,
          [],
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<void> toggleFlash() => (super.noSuchMethod(
        Invocation.method(
          #toggleFlash,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pauseCamera() => (super.noSuchMethod(
        Invocation.method(
          #pauseCamera,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopCamera() => (super.noSuchMethod(
        Invocation.method(
          #stopCamera,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeCamera() => (super.noSuchMethod(
        Invocation.method(
          #resumeCamera,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SystemFeatures> getSystemFeatures() => (super.noSuchMethod(
        Invocation.method(
          #getSystemFeatures,
          [],
        ),
        returnValue: _i5.Future<_i2.SystemFeatures>.value(_FakeSystemFeatures_0(
          this,
          Invocation.method(
            #getSystemFeatures,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SystemFeatures>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> scanInvert(bool? isScanInvert) => (super.noSuchMethod(
        Invocation.method(
          #scanInvert,
          [isScanInvert],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i8.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.XFile?> pickImage({
    required _i3.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i5.Future<_i3.XFile?>.value(),
      ) as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<List<_i3.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i5.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
      ) as _i5.Future<List<_i3.XFile>>);

  @override
  _i5.Future<_i3.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i5.Future<_i3.XFile?>.value(),
      ) as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<List<_i3.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i5.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
      ) as _i5.Future<List<_i3.XFile>>);

  @override
  _i5.Future<_i3.XFile?> pickVideo({
    required _i3.ImageSource? source,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i5.Future<_i3.XFile?>.value(),
      ) as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<_i3.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i5.Future<_i3.LostDataResponse>.value(_FakeLostDataResponse_1(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i5.Future<_i3.LostDataResponse>);

  @override
  bool supportsImageSource(_i3.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
      ) as bool);
}
