import 'package:karmayogi_mobile/models/index.dart';
import 'package:karmayogi_mobile/ui/pages/_pages/toc/model/language_map_model.dart';

class ConstantsTestUtil {
  static const String validMail = 'test@yopmail.com';
  static const String validPhone = '9000000000';
  static const String otp = '111111';
  static List<Course> courseList = [
    Course(
        appIcon: 'app-icon',
        contentId: 'test-id-1',
        courseCategory: 'test-course',
        primaryCategory: 'test-course',
        creatorIcon: '',
        creatorLogo: '',
        cumulativeTracking: false,
        description: 'test-descrition',
        id: 'test-1',
        instructions: '',
        isExternalCourse: false,
        issuedCertificates: [],
        leafNodes: [],
        name: 'test-name',
        source: '',
        wfSurveyLink: '',
        additionalTags: [],
        duration: '10',
        programDuration: '10',
        status: 'live',
        endDate: '2025-01-06 14:25:47.123456',
        licence: '',
        language: 'English',
        sectorDetails: [],
        compatibilityLevel: 0,
        contextLockingType: 'none',
        languageMap: LanguageMapV1(languages: {}),
        rating: 0.0,
    ),
    Course(
        appIcon: 'app-icon',
        contentId: 'test-id-2',
        courseCategory: 'test-course',
        primaryCategory: 'test-course',
        creatorIcon: '',
        creatorLogo: '',
        cumulativeTracking: false,
        description: 'test-descrition',
        id: 'test-2',
        instructions: '',
        isExternalCourse: false,
        issuedCertificates: [],
        leafNodes: [],
        name: 'test-name',
        source: '',
        wfSurveyLink: '',
        additionalTags: [],
        duration: '10',
        programDuration: '10',
        status: 'live',
        endDate: '2025-01-06 14:25:47.123456',
        licence: '',
        language: 'Hindi',
        sectorDetails: [],
        compatibilityLevel: 0,
        contextLockingType: 'none',
        languageMap: LanguageMapV1(languages: {}),
        rating: 0.0,
    ),
    Course(
        appIcon: 'app-icon',
        contentId: 'test-id-3',
        courseCategory: 'test-course',
        primaryCategory: 'test-course',
        creatorIcon: '',
        creatorLogo: '',
        cumulativeTracking: false,
        description: 'test-descrition',
        id: 'test-3',
        instructions: '',
        isExternalCourse: false,
        issuedCertificates: [],
        leafNodes: [],
        name: 'test-name',
        source: '',
        wfSurveyLink: '',
        additionalTags: [],
        duration: '10',
        programDuration: '10',
        status: 'live',
        endDate: '2025-01-06 14:25:47.123456',
        licence: '',
        language: 'Hindi',
        sectorDetails: [],
        compatibilityLevel: 0,
        contextLockingType: 'none',
        languageMap: LanguageMapV1(languages: {}),
        rating: 0.0,
        ),
    Course(
        appIcon: 'app-icon',
        contentId: 'test-id-4',
        courseCategory: 'test-course',
        primaryCategory: 'test-course',
        creatorIcon: '',
        creatorLogo: '',
        cumulativeTracking: false,
        description: 'test-descrition',
        id: 'test-4',
        instructions: '',
        isExternalCourse: false,
        issuedCertificates: [],
        leafNodes: [],
        name: 'test-name',
        source: '',
        wfSurveyLink: '',
        additionalTags: [],
        duration: '10',
        programDuration: '10',
        status: 'live',
        endDate: '2025-01-06 14:25:47.123456',
        licence: '',
        language: 'English',
        sectorDetails: [],
        compatibilityLevel: 0,
        contextLockingType: 'none',
        languageMap: LanguageMapV1(languages: {}),
        rating: 0.0,
    ),
  ];
  static Map courseJson = {
    'appIcon': 'app-icon',
    'contentId': 'test-id-1',
    'contentType': 'test-course',
    'creatorIcon': '',
    'creatorLogo': '',
    'cumulativeTracking': false,
    'description': 'test-descrition',
    'id': 'test-1',
    'instructions': '',
    'isExternalCourse': false,
    'issuedCertificates': [],
    'leafNodes': [],
    'name': 'test-name',
    'source': '',
    'wfSurveyLink': '',
    'additionalTags': [],
    'duration': '10',
    'programDuration': '10'
  };
  static List<String> doIdList = ['test-id-1', 'test-id-2'];
  static const String submit = 'submit';
  static const String header = 'test_header';
  static const String hintText = 'test_hintText';
  static const String orgFrameworkId = 'test_orgFrameworkId';
  static const String orgId = 'orgId';
  static const String department = 'test_department';
  static const String recomendationId = 'test_recommendationId';
}
